[package]
name = "bevy_animation_state_machine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.6.1"
bevy = "0.11"
graphlib = "0.6.3"
